serviceName: airflow
owner: data-engineering

service:
  logGroupName: airflow/ecs/fargate
  cidrBlock: 10.0.0.0
  baseUrl: http://localhost:8080
  imageVersion: latest

publicSubnet:
  1:
    cidrBlock: 10.0.1.0/24
    availabilityZone: a
  2:
    cidrBlock: 10.0.2.0/24
    availabilityZone: b
  3:
    cidrBlock: 10.0.3.0/24
    availabilityZone: c

metadataDb:
  instanceType: db.t3.micro
  port: 5432
  engine: aurora-postgresql
  engineMode: provisioned
  engineVersion: 11.7
  family: aurora-postgresql11
  deletionProtection: false
  enableHttpEndpoint: true
  storageEncrypted: true
  enableIAMDatabaseAuthentication: true
  secrets:
    rotationScheduleDays: 30
  parameters:
    maxConnections: 100


celeryBackend:
  InstanceType: cache.t3.small
  numNodes: 1
